# Generated by Django 3.2.8 on 2021-10-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='How_to_make',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_pic',
            new_name='project_pic',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
    ]
