# Generated by Django 3.2.8 on 2021-10-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211023_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ingredient',
        ),
    ]
